### ISSUE TITLE
docker images are tagged with the tag generated by the chart-releaser-action

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-airflow#101]
now that we use the chart-releaser action, we can automate the tagging of the docker images with the same tag that was generated by the chart-releaser-action.

The idea would be to avoid having values like this in a release: https://github.com/bcgov/cas-ciip-portal/blob/61d938c5efc2c4cb7859e30ccae1da27cfccbd8b/helm/cas-ciip-portal/values.yaml#L4

AC:
- [ ] updated CI rule to run the tagging job with the generated release tag
- [ ]  `tag` in the values.yaml file needs to be updated automatically as part of the release process - this can probably be done by using a templating `tpl ( ... ) ` call? Or by CI as well?

**Comment by pbastia** [comment]
Once this is done, the users of the `cas-airflow-dag-trigger` chart won't have to specify an image tag

**Comment by matthieu-foucault** [comment]
because the tag push is done by the chart-releaser action, it does not have access to the CircleCI context and thus cannot access the shared secret to push to GCR or log into Docker. Sounds like it's time to migrate this repo to GH actions
