### ISSUE TITLE
Bug: nginx reload dag fails when crunchy postgres operator is installed in that namespace

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-airflow#132]
### Describe the Bug:

This is a combination of:
- The monitoring sidecar generates an empty projected volume in its yaml, in the database pods `cas-cif-postgres-pgha1-<...>-N`
  ```
   - name: exporter-config
     projected:
     defaultMode: 420
     sources: null
  ```
- The python kubernetes API strictly enforces the projected volume spec when parsing responses from the cluster on api calls like `list_namespaced_pod(...)`, which is why we're getting this error: `ValueError: Invalid value for 'sources, must not be 'None'`

the issue is very similar to this https://github.com/kubernetes-client/python/issues/895 , so one avenue to fixing in the short term is to monkey-patch in a similar way - especially that we're not doing anything with that data in this DAG, we're just listing the pods to find the nginx ones. 

**Probability (how likely the bug is to happen, scored from 1-5): 5**

**Effect (how bad the bug is when it does happen, scored from 1-5): 3**
There is a workaround: restart the nginx pods manually

### Steps to reproduce
Install the postgres operator in a namespace, then run the `reload_nginx_containers` for that namespace (no need to actually have nginx containers present)

### Dev Details
the issue is very similar to this https://github.com/kubernetes-client/python/issues/895 , so one avenue to fixing in the short term is to monkey-patch in a similar way - especially that we're not doing anything with that data in this DAG, we're just listing the pods to find the nginx ones. 

probably something like:
```
 from kubernetes.client.models.v1_projected_volume_source import V1ProjectedVolumeSource
  def sources(self, names):
      self._sources = sources or []
  V1ContainerImage.sources = V1ContainerImage.sources.setter(sources)
```

[this](https://github.com/kubernetes-client/python/blob/821618feb3456674ea586047b972b3ae7559fa42/kubernetes/client/models/v1_projected_volume_source.py#L103) is the context of what we're trying to patch

**Comment by matthieu-foucault** [comment]
This might be a good opportunity to investigate using a https://github.com/BCDevOps/certbot deployment in our namespaces. We could contribute a helm chart to that repo.

This would require some updates to our cif chart to ensure it is not overriding the certs (which would be stored in the route object), but it would allow us to remove the dependency to the nginx container.

We would want to configure email alerts in sysdig to keep that feature, currently provided by airflow
