### ISSUE TITLE
Bug - Airflow: triggering a kubernetes cron job will fail if the cluster takes too long instantiating a job

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-airflow#139]
`trigger_k8s_cronjob.py` contains a flaw where [it waits an arbitrary 10 second](https://github.com/bcgov/cas-airflow/blob/develop/dags/trigger_k8s_cronjob.py#L78) for a job to be created from the cronjob.
This can cause a failure if the cluster is slow, because the retrieved list of matching jobs will be empty.

Action Item:
Retry getting the jobs (with logging) if the returned list is empty, and abort with a much longer timeout. Maybe we can retry indefinitely and let the cluster timeout the job instead?

**Comment by pbastia** [comment]
This is a good introduction to airflow for people who haven't worked much with our airflow deployment yet @BCerki @Sepehr-Sobhani @mikevespi @gurjmatharu

**Comment by LindsayMacfarlane** [comment]
Thank you @tmastrom! I don't believe there is anything I need to test for this bug, but please let me know if otherwise.
