### ISSUE TITLE
Airflow: login should use GitHub teams to log people in

### ISSUE THREAD

**Issue by pbastia** [bcgov/cas-airflow#145]
currently, we're using the same password stored in an openshift secret. 

Look into integration with our Github team ([docs](https://airflow.apache.org/docs/apache-airflow/2.2.5/security/webserver.html#example-using-team-based-authorization-with-github-oauth))

**Comment by LindsayMacfarlane** [comment]
@mikevespi - awesome! Anything I need to test out?

**Comment by LindsayMacfarlane** [comment]
@mikevespi - following up to see if there is anything that needs testing or if I can move to PO approved?

**Comment by LindsayMacfarlane** [comment]
@mikevespi - @pbastia walked me through logging in with GitHub. Worked very smoothly. Thank you!

**Comment by mikevespi** [comment]
Sorry I missed that Lindsay! Notifications stopped going to my focus inbox out of nowhere!

**Comment by pbastia** [comment]
This could be deployed to test and prod, is there anything additional we need to do @mikevespi @dleard ?

**Comment by mikevespi** [comment]
Unless there is someone from outside of our team who we give access to for some reason, then I don't believe so but I will double check.
