### ISSUE TITLE
As a maintainer, I want DAGs to be in the application repositories

### ISSUE THREAD

**Issue by matthieu-foucault** [bcgov/cas-airflow#76]
Using a DELL ECS or GCP bucket, we could ensure that correct version of the DAGs are used when deploying our application, and we could host the DAGs code in the applications git repositories instead of this repository

- [ ] create a dag that fetches DAG files from a given <git url, path, ref> config and writes them to the DAGs PVC (needs to be enabled in airflow helm chart)
- [ ] each application uses airflow-dag-trigger job (created in #91) to trigger the above DAG for its own repo.

- dag refresh time might need tweaking

Possibly helpful blog post on breaking up the dag monorepo:
https://tech.scribd.com/blog/2020/breaking-up-the-dag-repo.html
Idea to do something similar with GCS:
https://github.com/GoogleCloudPlatform/gcsfuse
Related Airflow 2.0 improvement proposal:
https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-5+Remote+DAG+Fetcher

**Comment by pbastia** [comment]
No DELL ECS needed, we can just use airflow to round up and collect dags when it gets a signal from the various repos exposing dags

**Comment by pbastia** [comment]
This card has been split up and can be marked complete
